# Generated by Django 2.0.5 on 2018-07-05 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='punishmentreward',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Employee'),
        ),
        migrations.AddField(
            model_name='punishmentreward',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punishment_rewards', related_query_name='punishment_rewards', to='assessment.Season'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments_as_assessed', related_query_name='assessments_as_assessed', to='authentication.Employee'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments_as_assessor', related_query_name='assessments_as_assessor', to='authentication.Employee'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', related_query_name='assessments', to='assessment.Season'),
        ),
    ]
