# Generated by Django 2.0.5 on 2018-07-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_auto_20180705_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='scales',
            field=models.ManyToManyField(to='assessment.Scale', verbose_name='معیارها'),
        ),
        migrations.AlterField(
            model_name='qualitativecriterion',
            name='choices',
            field=models.CharField(max_length=20, verbose_name='انتخاب\u200cها'),
        ),
    ]
