# Generated by Django 2.0.5 on 2018-07-05 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_auto_20180705_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='scaleanswer',
            name='carried_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qualitativecriterion',
            name='choices',
            field=models.CharField(max_length=200, verbose_name='انتخاب\u200cها'),
        ),
        migrations.AlterField(
            model_name='scaleanswer',
            name='qualitativeAnswer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scaleanswer',
            name='quantitativeAnswer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scaleanswer',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Scale'),
        ),
    ]
