# Generated by Django 2.0.5 on 2018-07-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_auto_20180712_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='startDate',
        ),
        migrations.AddField(
            model_name='season',
            name='title',
            field=models.CharField(default='s1', max_length=100, verbose_name='عنوان'),
            preserve_default=False,
        ),
    ]
