# Generated by Django 2.0.5 on 2018-07-12 11:08

import assessment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_auto_20180712_1428'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='season',
            managers=[
                ('objects', assessment.models.SeasonManager()),
            ],
        ),
        migrations.AlterField(
            model_name='punishmentreward',
            name='method',
            field=models.TextField(verbose_name='روش'),
        ),
        migrations.AlterField(
            model_name='scaleanswer',
            name='carried_on',
            field=models.BooleanField(default=False, verbose_name='انجام\u200cشده'),
        ),
        migrations.AlterField(
            model_name='scaleanswer',
            name='qualitativeAnswer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='پاسخ کیفی'),
        ),
        migrations.AlterField(
            model_name='scaleanswer',
            name='quantitativeAnswer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='پاسخ کمی'),
        ),
    ]
