# Generated by Django 2.0.5 on 2018-07-12 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_auto_20180712_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punishmentreward',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='punishmentreward',
            name='season',
        ),
        migrations.AddField(
            model_name='punishmentreward',
            name='assessment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='assessment.Assessment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='punishmentreward',
            name='method',
            field=models.TextField(blank=True, null=True, verbose_name='روش'),
        ),
        migrations.AlterField(
            model_name='punishmentreward',
            name='type',
            field=models.CharField(choices=[('R', 'تشویق'), ('P', 'تنبیه'), ('N', 'نه تشویق و نه تنبیه')], default='N', max_length=1, verbose_name='نوع'),
        ),
    ]
