# Generated by Django 2.0.5 on 2018-07-17 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('C', 'create'), ('E', 'edit'), ('R', 'read')], max_length=50)),
                ('object', models.CharField(choices=[('A', 'Assessment'), ('E', 'Employee'), ('P', 'PunishmentReward'), ('S', 'Scale'), ('U', 'Unit'), ('N', 'Season')], max_length=60)),
            ],
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='job',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_authentication.job_set+', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', related_query_name='user', to='authentication.Job', verbose_name='نقش'),
        ),
        migrations.AddField(
            model_name='job',
            name='permissions',
            field=models.ManyToManyField(to='authentication.Permission'),
        ),
    ]
