# Generated by Django 2.0.5 on 2018-06-19 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Unit', verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='father_name',
            field=models.CharField(max_length=30, null=True, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=15, null=True, verbose_name='موبایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(max_length=10, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personnel_code',
            field=models.CharField(max_length=8, null=True, verbose_name='شماره پرسنلی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_of_birth',
            field=models.IntegerField(null=True, verbose_name='سال تولد'),
        ),
    ]
