# Generated by Django 2.0.5 on 2018-06-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20180619_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='father_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_of_birth',
            field=models.IntegerField(blank=True, null=True, verbose_name='سال تولد'),
        ),
    ]
