# Generated by Django 2.0.5 on 2018-07-17 19:03

from django.db import migrations
from authentication.models import ACTION_CHOICES, OBJECT_CHOICES


def create_permissions(apps, schema_editor):
    Permission = apps.get_model("authentication", "Permission")
    for ac in ACTION_CHOICES:
        for oc in OBJECT_CHOICES:
            Permission.objects.create(action=ac[0], object=oc[0])


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20180717_2326'),
    ]

    operations = [
        migrations.RunPython(create_permissions)
    ]
